import { APIHeaderInfo, TEST_RESULTS } from '../components/API/API.data.types';
import { METHODS } from '../types/methods';

export const DUMMY_API_HEADER_INFO_LIST: APIHeaderInfo[] = [
  {
    apiId: 1,
    apiTitle: '특별한 계란 목록 가져오기',
    apiDescription: '특별한 계란 목록 가져옵니다.. 주절주절',
    method: METHODS.get,
    isSecure: false,
    manager: { id: 1, nickname: '김현진' },
    nominalUrl: '/api/eggs/special',
    testStatus: TEST_RESULTS.SUCCESS,
  },
  {
    apiId: 2,
    apiTitle: '사용자 정보 업데이트',
    apiDescription: '사용자 정보 업데이트합니다.. 주절주절',
    method: METHODS.post,
    isSecure: true,
    manager: { id: 2, nickname: '김현진' },
    nominalUrl: '/api/users/update',
    testStatus: TEST_RESULTS.FAIL,
  },
  {
    apiId: 3,
    apiTitle: '상품 목록 조회',
    apiDescription: '상품 목록을 조회합니다.. 주절주절',
    method: METHODS.get,
    isSecure: false,
    manager: { id: 3, nickname: '장철현' },
    nominalUrl: '/api/products/list',
    testStatus: TEST_RESULTS.NOT_TESTED,
  },
  {
    apiId: 4,
    apiTitle: '회원 탈퇴 처리',
    apiDescription: '회원 탈퇴를 처리합니다.. 주절주절',
    method: METHODS.delete,
    isSecure: true,
    manager: { id: 3, nickname: '장철현' },
    nominalUrl: '/api/users/delete',
    testStatus: TEST_RESULTS.SUCCESS,
  },
  {
    apiId: 5,
    apiTitle: '주문 상태 변경',
    apiDescription: '주문 상태를 변경합니다.. 주절주절',
    method: METHODS.put,
    isSecure: true,
    manager: { id: 4, nickname: '박민희' },
    nominalUrl: '/api/orders/status',
    testStatus: TEST_RESULTS.NOT_TESTED,
  },
  {
    apiId: 6,
    apiTitle: '주문 상태 갱신',
    apiDescription: '주문 상태를 갱신합니다.. 주절주절',
    method: METHODS.patch,
    isSecure: true,
    manager: { id: 4, nickname: '박민희' },
    nominalUrl: '/api/orders/status/update',
    testStatus: TEST_RESULTS.NOT_TESTED,
  },
  {
    apiId: 7,
    apiTitle: '로그인 세션 검증',
    apiDescription: '로그인 세션을 검증합니다.. 주절주절',
    method: METHODS.get,
    isSecure: true,
    manager: { id: 3, nickname: '장철현' },
    nominalUrl: '/api/session/validate',
    testStatus: TEST_RESULTS.FAIL,
  },
];
