FROM gradle:8.9.0-jdk17 AS builder
WORKDIR /shooot
COPY . .

RUN chmod +x ./gradlew
RUN ./gradlew bootJar

# 2. 패키지 단계
FROM amazoncorretto:17
COPY --from=builder /shooot/build/libs/*.jar /app.jar

EXPOSE 8080

CMD ["java", "-jar", "/app.jar"]
